### ISSUE TITLE
Timing & Source code

### ISSUE THREAD

**Issue by mdblack98** [westoncampbell/SpyPlusPlus#1]
I'd like to add timing to the events...trying to track down a problem with some graphics calls and need to know which call is taking all the time.
I'd do it myself but there's no source code here.
Is source available?

**Comment by westoncampbell** [comment]
> I'd like to add timing to the events...trying to track down a problem with some graphics calls and need to know which call is taking all the time.
> I'd do it myself but there's no source code here.
> Is source available?

I just uploaded these for archival purposes. I do not have any source code. Sorry for any inconvenience!
